version: '3.8'

services:
  rta.kafka:
    image: spotify/kafka:latest
    container_name: rta.kafka
    hostname: kafkaserver
    ports:
        - 2181:2181
        - 9092:9092
    environment:
        - ADVERTISED_HOST=kafkaserver
        - ADVERTISED_PORT=9092
        - AUTO_CREATE_TOPICS=true
    command: >
        bash -c
        "(sleep 5s &&
        /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh
        --create
        --zookeeper
        localhost:2181 --replication-factor 1 --partitions 1
        --topic rtaTestTopic &) && (supervisord -n)"
    networks:
        - rta-dev

  rta.producer:
    image: rta.producer
    container_name: rta.producer
    hostname: rta.producer
    ports:
        - 8000:80
        - 8011:443
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ADVERTISED_HOST=kafkaserver
        - ADVERTISED_PORT=9092
        - TOPIC=rtaTestTopic
    build:
        context: .
        dockerfile: rta.producer/Dockerfile
    networks:
        - rta-dev

  rta.consumerone:
    image: rta.consumerone
    container_name: rta.consumerone
    environment:
        - ADVERTISED_HOST=kafkaserver
        - ADVERTISED_PORT=9092
        - TOPIC=rtaTestTopic
    build:
        context: .
        dockerfile: rta.consumerone/Dockerfile
    networks:
        - rta-dev

  rta.consumertwo:
    image: rta.consumertwo
    container_name: rta.consumertwo
    environment:
        - ADVERTISED_HOST=kafkaserver
        - ADVERTISED_PORT=9092
        - TOPIC=rtaTestTopic
    build:
        context: .
        dockerfile: rta.consumertwo/Dockerfile
    networks:
        - rta-dev

networks:
  rta-dev:
    driver: bridge 